In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('../dataset2/dataset_2A_interest_growth.csv',index_col=0)

In [5]:
df.sort_values(by=['거래소코드', '회계년도'], inplace=True)

In [6]:
# Convert '회계년도' to datetime format
df['회계년도'] = pd.to_datetime(df['회계년도'])

# Function to check if there are at least 3 consecutive years in a group
def has_three_consecutive_years(group):
    # Sort the years
    years = group['회계년도'].dt.year.sort_values()
    # Check for at least 3 consecutive years
    return any((years.shift(-2) - years) == 2)

# Group by '거래소코드' and filter out groups that don't have 3 consecutive years
filtered_data = df.groupby('거래소코드').filter(has_three_consecutive_years)

# Show the result
filtered_data

,회사명,거래소코드,회계년도,감사의견코드,산업코드,산업명,설립일,기업규모코드,기업규모명,통계청 한국표준산업분류 코드 10차(대분류),...,이자보상배율,new_총자본증가율,new_총부채증가율,new_순이익증가율,new_유형자산증가율,new_유동자산증가율,new_영업이익증가율,new_재고자산증가율,new_매출액증가율,new_비유동자산증가율
70560,(주)포스코건설,10000,2012-12-01,UQ,64102,토목 건설업,1994/12/01,10.0,대기업,41,...,1479.098523,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
70561,(주)포스코건설,10000,2013-12-01,UQ,64102,토목 건설업,1994/12/01,10.0,대기업,41,...,1384.016443,2.842294,-22.408393,-71.478710,40.756393,-18.258059,13.631720,-16.164419,14.016854,4.081387
70562,(주)포스코건설,10000,2014-12-01,UQ,64102,토목 건설업,1994/12/01,10.0,대기업,41,...,633.408037,0.143478,-7.484781,-86.472926,5.344684,-12.449193,-31.415835,-8.092776,-6.396890,17.867219
70563,(주)포스코건설,10000,2015-12-01,UQ,64102,토목 건설업,1994/12/01,10.0,대기업,41,...,733.133307,14.401493,-4.837130,127.038293,-4.509898,6.351912,-11.590310,-34.770304,-13.012219,-1.042386
70564,(주)포스코건설,10000,2016-12-01,UQ,64102,토목 건설업,1994/12/01,10.0,대기업,41,...,-808.461957,-23.096221,10.876742,-2616.490936,-10.676382,-5.085581,-173.802637,54.677241,-15.921085,-8.134513
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
221455,주식회사두루안,101635,2021-12-01,UQ,105802,소프트웨어 개발 및 공급업,2007/10/15,20.0,중소기업,58,...,215.801478,26.187846,-3.359280,317.304431,-1.374490,58.085287,-7.162331,7.322329,1.872254,-1.302387
221456,주식회사두루안,101635,2022-12-01,UQ,105802,소프트웨어 개발 및 공급업,2007/10/15,20.0,중소기업,58,...,-421.159620,10.028442,36.617113,-51.677152,54.399781,10.261314,-403.105893,63.082647,-12.227925,27.676594
16765,넬코리아주식회사,101667,2020-12-01,NaN,64102,토목 건설업,2017/08/08,20.0,중소기업,41,...,-1358.509774,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16766,넬코리아주식회사,101667,2021-12-01,QS,64102,토목 건설업,2017/08/08,20.0,중소기업,41,...,-1111.179691,408.324797,20.291910,190.228461,13.969112,-23.104733,173.681224,-28.716629,-14.067465,64.013882
16767,넬코리아주식회사,101667,2022-12-01,UQ,64102,토목 건설업,2017/08/08,0.0,NaN,41,...,-513.254819,42.821923,-8.531172,-46.690857,-25.593917,-47.054982,-21.655125,-70.730416,-45.895072,10.800214

In [7]:
filtered_data.to_csv('../dataset2/data2A_첫행날리기전.csv')

In [8]:
filtered_data.sort_values(by=['거래소코드', '회계년도'], inplace=True)
# Group by '거래소코드' and remove the first row of each group
filtered_data_grouped = filtered_data.groupby('거래소코드').apply(lambda x: x.iloc[1:]).reset_index(drop=True)

# Show the result
filtered_data_grouped.head(), len(filtered_data_grouped)

(        회사명  거래소코드       회계년도 감사의견코드   산업코드         산업명         설립일  기업규모코드  \
 0  (주)포스코건설  10000 2013-12-01     UQ  64102      토목 건설업  1994/12/01    10.0
 1  (주)포스코건설  10000 2014-12-01     UQ  64102      토목 건설업  1994/12/01    10.0
 2  (주)포스코건설  10000 2015-12-01     UQ  64102      토목 건설업  1994/12/01    10.0
 3  (주)포스코건설  10000 2016-12-01     UQ  64102      토목 건설업  1994/12/01    10.0
 4  (주)포스코건설  10000 2017-12-01     UQ  64102      토목 건설업  1994/12/01    10.0

   기업규모명  통계청 한국표준산업분류 코드 10차(대분류)  ...       이자보상배율  new_총자본증가율  new_총부채증가율  \
 0   대기업                        41  ...  1384.016443    2.842294  -22.408393
 1   대기업                        41  ...   633.408037    0.143478   -7.484781
 2   대기업                        41  ...   733.133307   14.401493   -4.837130
 3   대기업                        41  ...  -808.461957  -23.096221   10.876742
 4   대기업                        41  ...   758.927656    1.397914    5.142955

     new_순이익증가율  new_유형자산증가율  new_유동자산증가율  new_영업이익증가율  new_재고자산증가율  \
 0   -71.478710    40.756393   -18.258059    13.631720   -16.164419
 1   -86.472926     5.344684   -12.449193   -31.415835    -8.092776
 2   127.038293    -4.509898     6.351912   -11.590310   -34.770304
 3 -2616.490936   -10.676382    -5.085581  -173.802637    54.677241
 4  -108.096322     6.969776   -11.399067  -256.938856   -19.424219

    new_매출액증가율  new_비유동자산증가율
 0   14.016854      4.081387
 1   -6.396890     17.867219
 2  -13.012219     -1.042386
 3  -15.921085     -8.134513
 4   14.943191     36.635257

 [5 rows x 159 columns],
 202516)

In [12]:
filtered_data_grouped.to_csv('../dataset2/data2A_첫행날림.csv')

In [13]:
filtered_data_grouped[filtered_data_grouped['이자보상배율'].isnull() == True][['회사명','회계년도','이자보상배율','영업이익(손실)','이자비용']]

               회사명       회계년도  이자보상배율  영업이익(손실)  이자비용
649      신대성전기주식회사 2017-12-01     NaN       0.0   0.0
650      신대성전기주식회사 2018-12-01     NaN       0.0   0.0
15654      우미건설(주) 2022-12-01     NaN       0.0   0.0
21424      주식회사앰배텔 2021-12-01     NaN       0.0   0.0
21425      주식회사앰배텔 2022-12-01     NaN       0.0   0.0
...            ...        ...     ...       ...   ...
201793      도안캐슬1차 2022-12-01     NaN       0.0   0.0
202482       (주)황지 2021-12-01     NaN       NaN   NaN
202484    주식회사골드쌔들 2021-12-01     NaN       NaN   NaN
202486     주식회사더맘마 2021-12-01     NaN       NaN   NaN
202500  대운가스프랜트(주) 2022-03-01     NaN       NaN   NaN

[71 rows x 5 columns]