In [2]:
import pandas as pd

In [24]:
df = pd.read_csv('../dataset2/data2A_첫행날리기전_부도이후날리고y라벨링.csv', index_col=0)

In [25]:
df[df['y']==1]

,회사명,거래소코드,회계년도,감사의견코드,산업코드,산업명,설립일,기업규모코드,기업규모명,통계청 한국표준산업분류 코드 10차(대분류),...,new_유형자산증가율,new_유동자산증가율,new_영업이익증가율,new_재고자산증가율,new_매출액증가율,new_비유동자산증가율,감사의견_y,자본잠식률_100,자본잠식률_50,y
22,국제종합기계(주),10002,2012-12-01,UQ,32902,특수 목적용 기계 제조업,1968/06/30,10.0,대기업,29,...,NaN,NaN,NaN,NaN,NaN,NaN,a,B,c,1
134,대한상선주식회사,10023,2012-12-01,UQ,85001,해상 운송업,1983/09/01,30.0,중견기업,50,...,NaN,NaN,NaN,NaN,NaN,NaN,a,B,c,1
220,글로웨이(주),10037,2015-12-01,DU,64102,토목 건설업,1956/09/03,30.0,중견기업,41,...,-91.951919,-55.347739,390.905642,-35.219520,-32.332270,-55.805610,A,B,c,1
288,주식회사케이티엔지니어링,10050,2013-12-01,DU,106102,전기 통신업,1986/05/21,10.0,대기업,42,...,-26.423982,21.939725,125.314686,-26.757118,14.352635,-8.606761,A,b,c,1
413,프라임개발(주),10071,2012-12-01,UQ,64101,건물 건설업,1988/08/18,30.0,중견기업,41,...,NaN,NaN,NaN,NaN,NaN,NaN,a,B,c,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
177560,에너콘코리아유한회사,101435,2020-12-01,NaN,74605,기계장비 및 관련 물품 도매업,2015/10/08,20.0,중소기업,46,...,NaN,NaN,NaN,NaN,NaN,NaN,a,B,c,1
177564,주식회사팩스,101490,2020-12-01,NaN,137001,자연과학 및 공학 연구개발업,2019/04/19,20.0,중소기업,70,...,NaN,NaN,NaN,NaN,NaN,NaN,a,B,c,1
177568,주식회사정진애드,101528,2020-12-01,NaN,64101,건물 건설업,2011/05/23,20.0,중소기업,41,...,NaN,NaN,NaN,NaN,NaN,NaN,a,B,c,1
177570,주식회사제이케이글로벌,101561,2021-12-01,QS,31002,수산물 가공 및 저장 처리업,2017/11/15,20.0,중소기업,10,...,-8.181977,178.648993,-23.792792,-40.060176,5.384587,-8.091167,A,b,c,1
177577,넬코리아주식회사,101667,2020-12-01,NaN,64102,토목 건설업,2017/08/08,20.0,중소기업,41,...,NaN,NaN,NaN,NaN,NaN,NaN,a,B,c,1

In [26]:
# 거래소 코드와 회계년도를 기준으로 정렬
df = df.sort_values(by=['거래소코드', '회계년도'])

## Re-try processing the dataframe based on the specified conditions

# Iterate through the dataframe
for i in range(1, len(df)):
    # Check if current row's 'y' value is 1
    if df.loc[i, 'y'] == 1:
        # Check if the exchange code is the same as the previous row
        if df.loc[i, '거래소코드'] == df.loc[i-1, '거래소코드']:
            # Check if the previous row's '자본잠식률_50' is 'C'
            if df.loc[i-1, '자본잠식률'] >= 50:
                # Set the previous row's 'y' value to 1
                df.loc[i-1, 'y'] = 1

# Display the first few rows of the dataframe to verify the changes
df.head()

,회사명,거래소코드,회계년도,감사의견코드,산업코드,산업명,설립일,기업규모코드,기업규모명,통계청 한국표준산업분류 코드 10차(대분류),...,new_유형자산증가율,new_유동자산증가율,new_영업이익증가율,new_재고자산증가율,new_매출액증가율,new_비유동자산증가율,감사의견_y,자본잠식률_100,자본잠식률_50,y
0,(주)포스코건설,10000,2012-12-01,UQ,64102,토목 건설업,1994/12/01,10.0,대기업,41,...,NaN,NaN,NaN,NaN,NaN,NaN,a,b,c,0
1,(주)포스코건설,10000,2013-12-01,UQ,64102,토목 건설업,1994/12/01,10.0,대기업,41,...,40.756393,-18.258059,13.631720,-16.164419,14.016854,4.081387,a,b,c,0
2,(주)포스코건설,10000,2014-12-01,UQ,64102,토목 건설업,1994/12/01,10.0,대기업,41,...,5.344684,-12.449193,-31.415835,-8.092776,-6.396890,17.867219,a,b,c,0
3,(주)포스코건설,10000,2015-12-01,UQ,64102,토목 건설업,1994/12/01,10.0,대기업,41,...,-4.509898,6.351912,-11.590310,-34.770304,-13.012219,-1.042386,a,b,c,0
4,(주)포스코건설,10000,2016-12-01,UQ,64102,토목 건설업,1994/12/01,10.0,대기업,41,...,-10.676382,-5.085581,-173.802637,54.677241,-15.921085,-8.134513,a,b,c,0

In [27]:
df[df['y']==1]

,회사명,거래소코드,회계년도,감사의견코드,산업코드,산업명,설립일,기업규모코드,기업규모명,통계청 한국표준산업분류 코드 10차(대분류),...,new_유형자산증가율,new_유동자산증가율,new_영업이익증가율,new_재고자산증가율,new_매출액증가율,new_비유동자산증가율,감사의견_y,자본잠식률_100,자본잠식률_50,y
22,국제종합기계(주),10002,2012-12-01,UQ,32902,특수 목적용 기계 제조업,1968/06/30,10.0,대기업,29,...,NaN,NaN,NaN,NaN,NaN,NaN,a,B,c,1
134,대한상선주식회사,10023,2012-12-01,UQ,85001,해상 운송업,1983/09/01,30.0,중견기업,50,...,NaN,NaN,NaN,NaN,NaN,NaN,a,B,c,1
220,글로웨이(주),10037,2015-12-01,DU,64102,토목 건설업,1956/09/03,30.0,중견기업,41,...,-91.951919,-55.347739,390.905642,-35.219520,-32.332270,-55.805610,A,B,c,1
288,주식회사케이티엔지니어링,10050,2013-12-01,DU,106102,전기 통신업,1986/05/21,10.0,대기업,42,...,-26.423982,21.939725,125.314686,-26.757118,14.352635,-8.606761,A,b,c,1
413,프라임개발(주),10071,2012-12-01,UQ,64101,건물 건설업,1988/08/18,30.0,중견기업,41,...,NaN,NaN,NaN,NaN,NaN,NaN,a,B,c,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
177560,에너콘코리아유한회사,101435,2020-12-01,NaN,74605,기계장비 및 관련 물품 도매업,2015/10/08,20.0,중소기업,46,...,NaN,NaN,NaN,NaN,NaN,NaN,a,B,c,1
177564,주식회사팩스,101490,2020-12-01,NaN,137001,자연과학 및 공학 연구개발업,2019/04/19,20.0,중소기업,70,...,NaN,NaN,NaN,NaN,NaN,NaN,a,B,c,1
177568,주식회사정진애드,101528,2020-12-01,NaN,64101,건물 건설업,2011/05/23,20.0,중소기업,41,...,NaN,NaN,NaN,NaN,NaN,NaN,a,B,c,1
177570,주식회사제이케이글로벌,101561,2021-12-01,QS,31002,수산물 가공 및 저장 처리업,2017/11/15,20.0,중소기업,10,...,-8.181977,178.648993,-23.792792,-40.060176,5.384587,-8.091167,A,b,c,1
177577,넬코리아주식회사,101667,2020-12-01,NaN,64102,토목 건설업,2017/08/08,20.0,중소기업,41,...,NaN,NaN,NaN,NaN,NaN,NaN,a,B,c,1

In [28]:
# Step 4: 
def remove_post_default_data(group):
    # 최초 부도 년도 설정
    default_year = group[group['y'] == 1]['회계년도'].min()
    
    # default 값이 nan이 아니면 크거나 같은 데이터만 가져옴
    if not pd.isnull(default_year):
        group = group[group['회계년도'] >= default_year]
    
    return group

# 회사명으로 그룹바이 후 함수 적용
df_filtered = df.groupby('거래소코드').apply(remove_post_default_data).reset_index(drop=True)

df_filtered.head()

,회사명,거래소코드,회계년도,감사의견코드,산업코드,산업명,설립일,기업규모코드,기업규모명,통계청 한국표준산업분류 코드 10차(대분류),...,new_유형자산증가율,new_유동자산증가율,new_영업이익증가율,new_재고자산증가율,new_매출액증가율,new_비유동자산증가율,감사의견_y,자본잠식률_100,자본잠식률_50,y
0,(주)포스코건설,10000,2012-12-01,UQ,64102,토목 건설업,1994/12/01,10.0,대기업,41,...,NaN,NaN,NaN,NaN,NaN,NaN,a,b,c,0
1,(주)포스코건설,10000,2013-12-01,UQ,64102,토목 건설업,1994/12/01,10.0,대기업,41,...,40.756393,-18.258059,13.631720,-16.164419,14.016854,4.081387,a,b,c,0
2,(주)포스코건설,10000,2014-12-01,UQ,64102,토목 건설업,1994/12/01,10.0,대기업,41,...,5.344684,-12.449193,-31.415835,-8.092776,-6.396890,17.867219,a,b,c,0
3,(주)포스코건설,10000,2015-12-01,UQ,64102,토목 건설업,1994/12/01,10.0,대기업,41,...,-4.509898,6.351912,-11.590310,-34.770304,-13.012219,-1.042386,a,b,c,0
4,(주)포스코건설,10000,2016-12-01,UQ,64102,토목 건설업,1994/12/01,10.0,대기업,41,...,-10.676382,-5.085581,-173.802637,54.677241,-15.921085,-8.134513,a,b,c,0

In [29]:
df_filtered[df_filtered['y']==1]

,회사명,거래소코드,회계년도,감사의견코드,산업코드,산업명,설립일,기업규모코드,기업규모명,통계청 한국표준산업분류 코드 10차(대분류),...,new_유형자산증가율,new_유동자산증가율,new_영업이익증가율,new_재고자산증가율,new_매출액증가율,new_비유동자산증가율,감사의견_y,자본잠식률_100,자본잠식률_50,y
22,국제종합기계(주),10002,2012-12-01,UQ,32902,특수 목적용 기계 제조업,1968/06/30,10.0,대기업,29,...,NaN,NaN,NaN,NaN,NaN,NaN,a,B,c,1
134,대한상선주식회사,10023,2012-12-01,UQ,85001,해상 운송업,1983/09/01,30.0,중견기업,50,...,NaN,NaN,NaN,NaN,NaN,NaN,a,B,c,1
217,글로웨이(주),10037,2015-12-01,DU,64102,토목 건설업,1956/09/03,30.0,중견기업,41,...,-91.951919,-55.347739,390.905642,-35.219520,-32.332270,-55.805610,A,B,c,1
284,주식회사케이티엔지니어링,10050,2013-12-01,DU,106102,전기 통신업,1986/05/21,10.0,대기업,42,...,-26.423982,21.939725,125.314686,-26.757118,14.352635,-8.606761,A,b,c,1
409,프라임개발(주),10071,2012-12-01,UQ,64101,건물 건설업,1988/08/18,30.0,중견기업,41,...,NaN,NaN,NaN,NaN,NaN,NaN,a,B,c,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
158576,에너콘코리아유한회사,101435,2020-12-01,NaN,74605,기계장비 및 관련 물품 도매업,2015/10/08,20.0,중소기업,46,...,NaN,NaN,NaN,NaN,NaN,NaN,a,B,c,1
158580,주식회사팩스,101490,2020-12-01,NaN,137001,자연과학 및 공학 연구개발업,2019/04/19,20.0,중소기업,70,...,NaN,NaN,NaN,NaN,NaN,NaN,a,B,c,1
158584,주식회사정진애드,101528,2020-12-01,NaN,64101,건물 건설업,2011/05/23,20.0,중소기업,41,...,NaN,NaN,NaN,NaN,NaN,NaN,a,B,c,1
158585,주식회사제이케이글로벌,101561,2021-12-01,QS,31002,수산물 가공 및 저장 처리업,2017/11/15,20.0,중소기업,10,...,-8.181977,178.648993,-23.792792,-40.060176,5.384587,-8.091167,A,b,c,1
158592,넬코리아주식회사,101667,2020-12-01,NaN,64102,토목 건설업,2017/08/08,20.0,중소기업,41,...,NaN,NaN,NaN,NaN,NaN,NaN,a,B,c,1

In [23]:
df_filtered.to_csv('../dataset2/data2A_라벨링11.csv')