In [111]:
import pandas as pd

In [122]:
df1 = pd.read_csv('../dataset/dataset_2A_label.csv', index_col= 0)
df2 = pd.read_csv('../dataset/dataset_2A_plus_feature.csv', index_col= 0)

In [123]:
df1

,회사명,거래소코드,회계년도,감사의견코드,산업코드,산업명,설립일,기업규모코드,기업규모명,통계청 한국표준산업분류 코드 10차(대분류),...,노동소득분배율,자본분배율,이윤분배율,법인세비용차감전(계속사업)손익,인건비,금융비용,임차료,조세공과,감가상각비,y
0,(주)포스코건설,10000,2012-12-01,UQ,64102,토목 건설업,1994/12/01,10.0,대기업,41,...,16.93,83.07,58.52,458072.46,100145.17,-419.33,11489.42,4456.67,17680.02,0
1,(주)포스코건설,10000,2013-12-01,UQ,64102,토목 건설업,1994/12/01,10.0,대기업,41,...,39.42,60.58,33.82,155753.76,115047.15,-14196.96,11115.02,5042.92,19116.94,0
2,(주)포스코건설,10000,2014-12-01,UQ,64102,토목 건설업,1994/12/01,10.0,대기업,41,...,54.85,45.15,6.04,35583.76,121320.85,21074.13,13187.29,5165.64,24839.25,0
3,(주)포스코건설,10000,2015-12-01,UQ,64102,토목 건설업,1994/12/01,10.0,대기업,41,...,50.03,49.97,13.35,55211.14,113666.26,14255.74,10594.08,5933.40,27515.47,0
4,(주)포스코건설,10000,2016-12-01,UQ,64102,토목 건설업,1994/12/01,10.0,대기업,41,...,0.00,0.00,0.00,-858337.57,167421.94,-64787.70,12881.66,5619.91,24626.08,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
232482,주식회사미소,107099,2022-12-01,QS,95501,일반 및 생활 숙박시설 운영업,2019/01/15,20.0,중소기업,55,...,49.93,50.07,-25.93,-270.83,521.50,310.71,5.46,49.00,428.56,1
232483,주식회사에스제이홀딩스,107127,2021-12-01,NaN,126801,부동산 임대 및 공급업,2018/09/28,20.0,중소기업,68,...,0.00,0.00,0.00,-3251.14,114.41,483.38,118.07,50.10,3.16,0
232484,주식회사에스제이홀딩스,107127,2022-12-01,UQ,126801,부동산 임대 및 공급업,2018/09/28,20.0,중소기업,68,...,0.00,0.00,0.00,-1999.09,199.68,995.60,102.84,71.08,1.68,0
232485,주식회사하나종합개발,107356,2021-12-01,NaN,126801,부동산 임대 및 공급업,2020/06/01,NaN,NaN,64,...,0.00,0.00,79.22,125.27,0.00,-0.06,15.44,0.08,0.00,0
232486,주식회사하나종합개발,107356,2022-12-01,DS,126801,부동산 임대 및 공급업,2020/06/01,0.0,NaN,64,...,0.00,0.00,41.20,272.47,0.00,24.00,50.87,204.98,0.00,1

In [125]:
df1['회계년도']=pd.to_datetime(df1['회계년도'],format='%Y-%m-%d')
df2['회계년도']=pd.to_datetime(df2['회계년도'],format='%Y/%m')

In [126]:
df3=df2[['회사명','거래소코드','회계년도','자본잠식률','이자보상배율']]

In [127]:
df2

,회사명,거래소코드,회계년도,자본,유동자산,당좌자산,재고자산,부채,유동부채,자본금,비유동자산,매출액(영업수익),당기순이익(순손실),유형자산,영업이익(손실),이자비용,자본잠식률,이자보상배율
0,(유)가든주류,97082,2019-12-01,11944553.0,21901897.0,19194354.0,2707543.0,21302019.0,9010854.0,150000.0,11344675.0,50510093.0,1559029.0,8663247.0,1991621.0,628271.0,-78.630353,3.170003
1,(유)가든주류,97082,2020-12-01,7132998.0,19573603.0,17669059.0,1904544.0,25807747.0,15246016.0,150000.0,13367142.0,44082032.0,466033.0,9629106.0,615380.0,476716.0,-46.553320,1.290873
2,(유)가든주류,97082,2021-12-01,7726049.0,20616946.0,19480241.0,1136705.0,21774189.0,11061466.0,150000.0,8883292.0,38043897.0,679904.0,4364016.0,136557.0,476252.0,-50.506993,0.286733
3,(유)가든주류,97082,2022-12-01,-24958607.0,5364069.0,4321968.0,1042101.0,34820255.0,15253448.0,150000.0,4497579.0,32820256.0,-4544326.0,3897139.0,-2749456.0,1914030.0,167.390713,-1.436475
4,(유)그룹세브코리아,13171,2019-12-01,20612901.0,47964840.0,27850389.0,20114451.0,30304375.0,30207802.0,1700000.0,2952436.0,185157076.0,9089557.0,1342574.0,12070148.0,468007.0,-11.125236,25.790529
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
296285,주식회사에이알티에스,72312,2018-12-01,3668744.0,4723122.0,2944011.0,1779111.0,9757778.0,3329056.0,400000.0,8703400.0,17719515.0,602005.0,8195524.0,751295.0,325784.0,-8.171860,2.306114
296286,주식회사에이알티에스,72312,2019-12-01,3731160.0,5475259.0,2984346.0,2490913.0,10973040.0,4125085.0,400000.0,9228941.0,19414595.0,462416.0,8161375.0,536131.0,316182.0,-8.327900,1.695640
296287,주식회사에이알티에스,72312,2020-12-01,4236849.0,5981029.0,4243291.0,1737738.0,10616436.0,2661065.0,400000.0,8872256.0,20325251.0,755689.0,8085460.0,794150.0,340929.0,-9.592123,2.329371
296288,주식회사에이알티에스,72312,2021-12-01,4892321.0,6891464.0,4187060.0,2704403.0,10718409.0,3156442.0,400000.0,8719266.0,19539179.0,655472.0,7995374.0,491334.0,320861.0,-11.230802,1.531299
296289,주식회사에이알티에스,72312,2022-12-01,5300432.0,7447061.0,4231346.0,3215715.0,10562519.0,9093068.0,400000.0,8415890.0,18591037.0,408110.0,7724356.0,730775.0,495347.0,-12.251080,1.475279

In [128]:
df3['자본잠식률'].isna().sum()

90

In [135]:
# Merging the two datasets on '회사명' and '회계년도'
merged_dataset = pd.merge(df1, df2, on=['회사명','거래소코드' ,'회계년도'], how='inner')

# Display the first few rows of the merged dataset
merged_dataset

,회사명,거래소코드,회계년도,감사의견코드,산업코드,산업명,설립일,기업규모코드,기업규모명,통계청 한국표준산업분류 코드 10차(대분류),...,유동부채,자본금,비유동자산,매출액(영업수익),당기순이익(순손실),유형자산,영업이익(손실),이자비용,자본잠식률,이자보상배율
0,(주)포스코건설,10000,2012-12-01,UQ,64102,토목 건설업,1994/12/01,10.0,대기업,41,...,4.065246e+09,183615000.0,1.795820e+09,7.041300e+09,346107173.0,49993457.0,355842987.0,24058099.0,-14.718530,14.790985
1,(주)포스코건설,10000,2013-12-01,UQ,64102,토목 건설업,1994/12/01,10.0,대기업,41,...,3.408481e+09,183615000.0,1.869114e+09,8.028269e+09,98714232.0,70368987.0,404350507.0,29215730.0,-15.165297,13.840164
2,(주)포스코건설,10000,2014-12-01,UQ,64102,토목 건설업,1994/12/01,10.0,대기업,41,...,2.840674e+09,183615000.0,2.203073e+09,7.514710e+09,13353147.0,74129987.0,277320417.0,43782270.0,-15.188490,6.334080
3,(주)포스코건설,10000,2015-12-01,UQ,64102,토목 건설업,1994/12/01,10.0,대기업,41,...,2.826397e+09,209033470.0,2.180108e+09,6.536879e+09,30316757.0,70786800.0,245178121.0,33442502.0,-15.267858,7.331333
4,(주)포스코건설,10000,2016-12-01,UQ,64102,토목 건설업,1994/12/01,10.0,대기업,41,...,3.290671e+09,209033470.0,2.002767e+09,5.496137e+09,-762918442.0,63229331.0,-180947918.0,22381748.0,-11.510598,-8.084620
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
230506,주식회사미소,107099,2022-12-01,QS,95501,일반 및 생활 숙박시설 운영업,2019/01/15,20.0,중소기업,55,...,8.069070e+05,500000.0,9.521313e+06,1.954618e+06,-270833.0,9479954.0,-69778.0,342407.0,-5.664570,-0.203787
230507,주식회사에스제이홀딩스,107127,2021-12-01,NaN,126801,부동산 임대 및 공급업,2018/09/28,20.0,중소기업,68,...,4.139361e+06,100000.0,1.185550e+05,0.000000e+00,-3251136.0,4420.0,-2767762.0,483376.0,38.354250,-5.725899
230508,주식회사에스제이홀딩스,107127,2022-12-01,UQ,126801,부동산 임대 및 공급업,2018/09/28,20.0,중소기업,68,...,3.878332e+07,100000.0,1.018330e+05,9.360581e+06,-1999091.0,1833.0,-1044113.0,997815.0,58.345170,-1.046399
230509,주식회사하나종합개발,107356,2021-12-01,NaN,126801,부동산 임대 및 공급업,2020/06/01,NaN,NaN,64,...,3.604679e+07,500000.0,3.491882e+07,5.427500e+05,111488.0,34862266.0,131521.0,0.0,-0.199846,inf
230510,주식회사하나종합개발,107356,2022-12-01,DS,126801,부동산 임대 및 공급업,2020/06/01,0.0,NaN,64,...,4.179273e+07,500000.0,4.058045e+07,1.911979e+06,227555.0,40498606.0,296503.0,24079.0,-0.654958,12.313759

In [136]:
merged_dataset.to_csv('../dataset/dataset_2A_plus_sh.csv')

In [134]:
merged_dataset[merged_dataset['회사명'] == '아크로산업개발(주)']

,회사명,거래소코드,회계년도,감사의견코드,산업코드,산업명,설립일,기업규모코드,기업규모명,통계청 한국표준산업분류 코드 10차(대분류),...,이윤분배율,법인세비용차감전(계속사업)손익,인건비,금융비용,임차료,조세공과,감가상각비,y,자본잠식률,이자보상배율
147805,아크로산업개발(주),69113,2013-12-01,NaN,126801,부동산 임대 및 공급업,2013/04/05,20.0,중소기업,68,...,0.0,-2438.44,163.91,-4.8,20.10,3.87,0.0,0,48.76880,-inf
147806,아크로산업개발(주),69113,2014-12-01,QS,126801,부동산 임대 및 공급업,2013/04/05,20.0,중소기업,68,...,0.0,-3364.91,502.63,533.4,57.04,11.36,57.8,1,148.31004,-4.095919