In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('../dataset/dataset_2A_del.csv',index_col=0)

In [3]:
# Step 2 : 회계년도를 datetime
df['회계년도'] = pd.to_datetime(df['회계년도'], format='%Y/%m')
df_sorted = df.sort_values(by=['거래소코드', '회계년도'])

# Step 3 : 감사의견코드 중 DI, DS DU, AG, QS가 존재하면 1 아니면 0
df_sorted['y'] = df_sorted['감사의견코드'].apply(lambda x: 1 if x in ['DI', 'DS', 'DU', 'AG', 'QS'] else 0)

In [4]:
# Step 4: 
def remove_post_default_data(group):
    # 최초 부도 년도 설정
    default_year = group[group['y'] == 1]['회계년도'].min()
    
    # default 값이 nan이 아니면 작거나 같은 데이터만 가져옴
    if not pd.isnull(default_year):
        group = group[group['회계년도'] <= default_year]
    
    return group

# 회사명으로 그룹바이 후 함수 적용
df_filtered = df_sorted.groupby('거래소코드').apply(remove_post_default_data).reset_index(drop=True)

df_filtered.head()

,회사명,거래소코드,회계년도,감사의견코드,산업코드,산업명,설립일,기업규모코드,기업규모명,통계청 한국표준산업분류 코드 10차(대분류),...,[제조]노동소득분배율,[제조]자본분배율,[제조]이윤분배율,[제조]법인세비용차감전(계속사업)손익(백만원),[제조]인건비(백만원),[제조]금융비용(백만원),[제조]임차료(백만원),[제조]조세공과(백만원),[제조]감가상각비(백만원),y
0,(주)포스코건설,10000,2012-12-01,UQ,64102,토목 건설업,1994/12/01,10.0,대기업,41,...,16.93,83.07,58.52,458072.46,100145.17,-419.33,11489.42,4456.67,17680.02,0
1,(주)포스코건설,10000,2013-12-01,UQ,64102,토목 건설업,1994/12/01,10.0,대기업,41,...,39.42,60.58,33.82,155753.76,115047.15,-14196.96,11115.02,5042.92,19116.94,0
2,(주)포스코건설,10000,2014-12-01,UQ,64102,토목 건설업,1994/12/01,10.0,대기업,41,...,54.85,45.15,6.04,35583.76,121320.85,21074.13,13187.29,5165.64,24839.25,0
3,(주)포스코건설,10000,2015-12-01,UQ,64102,토목 건설업,1994/12/01,10.0,대기업,41,...,50.03,49.97,13.35,55211.14,113666.26,14255.74,10594.08,5933.40,27515.47,0
4,(주)포스코건설,10000,2016-12-01,UQ,64102,토목 건설업,1994/12/01,10.0,대기업,41,...,0.00,0.00,0.00,-858337.57,167421.94,-64787.70,12881.66,5619.91,24626.08,0

In [5]:
df_filtered.to_csv('../dataset/dataset_2A_label_1.csv')

In [68]:
df_filtered[df_filtered['y'] == 1]

,회사명,거래소코드,회계년도,감사의견코드,산업코드,산업명,설립일,기업규모코드,기업규모명,통계청 한국표준산업분류 코드 10차(대분류),...,[제조]노동소득분배율,[제조]자본분배율,[제조]이윤분배율,[제조]법인세비용차감전(계속사업)손익(백만원),[제조]인건비(백만원),[제조]금융비용(백만원),[제조]임차료(백만원),[제조]조세공과(백만원),[제조]감가상각비(백만원),y
146,대한상선주식회사,10023,2015-12-01,DU,85001,해상 운송업,1983/09/01,30.0,중견기업,50,...,0.00,0.00,0.00,-156728.16,3658.25,11888.32,692.24,140.07,31269.85,1
236,글로웨이(주),10037,2015-12-01,DU,64102,토목 건설업,1956/09/03,30.0,중견기업,41,...,0.00,0.00,0.00,-108489.90,1893.25,2329.80,99.50,280.25,46.04,1
316,주식회사케이티엔지니어링,10050,2013-12-01,DU,106102,전기 통신업,1986/05/21,10.0,대기업,42,...,54.54,45.46,29.18,26465.12,41714.87,373.81,2899.87,1384.14,3648.95,1
443,프라임개발(주),10071,2014-12-01,DU,64101,건물 건설업,1988/08/18,30.0,중견기업,41,...,0.00,0.00,0.00,-577002.49,1082.03,32589.22,35.64,311.92,4923.20,1
551,시크리티스,10158,2012-12-01,QS,32004,기타 화학제품 제조업,1978/12/14,20.0,중소기업,20,...,0.00,0.00,0.00,-9971.33,854.62,483.74,588.34,2.45,702.70,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
232463,(주)안세,106907,2022-12-01,QS,74601,상품 중개업,1995/12/01,20.0,중소기업,46,...,214.68,-114.68,-132.87,-4403.44,7071.47,219.63,121.74,121.87,162.68,1
232472,(주)에이치엠티,106995,2022-12-01,QS,74608,상품 종합 도매업,2014/06/10,20.0,중소기업,46,...,26.03,73.97,51.48,3961.42,1502.49,-39.05,270.57,40.71,35.17,1
232480,(주)신우,107073,2022-12-01,QS,32509,기타 금속 가공제품 제조업,1993/07/22,20.0,중소기업,25,...,19.47,80.53,13.74,137.74,175.59,289.01,10.06,1.55,288.06,1
232482,주식회사미소,107099,2022-12-01,QS,95501,일반 및 생활 숙박시설 운영업,2019/01/15,20.0,중소기업,55,...,49.93,50.07,-25.93,-270.83,521.50,310.71,5.46,49.00,428.56,1
232486,주식회사하나종합개발,107356,2022-12-01,DS,126801,부동산 임대 및 공급업,2020/06/01,0.0,NaN,64,...,0.00,0.00,41.20,272.47,0.00,24.00,50.87,204.98,0.00,1